# Default values for kub-vol-bak.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: docker.io/jacksgt/kub-vol-bak
  tag: "latest"
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

restic:
  config:
  # https://restic.readthedocs.io/en/stable/030_preparing_a_new_repo.html
  RESTIC_REPOSITORY: ""
  RESTIC_PASSWORD: ""
  # more values to be passed as environment variables to restic
  # ...

  backup:
    schedule: "22 0 * * *"
    suspend: false

  forget:
    suspend: false
    schedule: "44 1 * * *"
    # according to which policy snapshots should be retained
    keepPolicy:
      last: 0
      hourly: 0
      daily: 0
      weekly: 0
      monthly: 0
      yearly: 0
      within: "30d"
      tags: []

  # When data associated to deleted snapshots should be deleted
  prune:
    # TODO: implement me
    suspend: false

  # Regularly check (some of) the data stored in the remote repository for errors
  # https://restic.readthedocs.io/en/stable/045_working_with_repos.html#checking-integrity-and-consistency
  check:
    # TODO: implement me
    suspend: false

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi


nodeSelector: {}

tolerations: []

affinity: {}
