---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kub-vol-bak.fullname" . }}-restic-config
  labels:
    {{- include "kub-vol-bak.labels" . | nindent 4 }}
data:
{{- range $key, $value := .Values.restic.config }}
  "{{ $key }}": "{{ $value | b64enc }}"
{{- end }}
