apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "kub-vol-bak.fullname" . }}-backup
  labels:
    {{- include "kub-vol-bak.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.backup.schedule | quote }}
  suspend: {{ .Values.backup.suspend }}
  concurrencyPolicy: Forbid
  jobTemplate:
    metadata:
      creationTimestamp: null
      labels:
        {{- include "kub-vol-bak.labels" . | nindent 8 }}
    spec:
      template:
        metadata:
          {{- with .Values.podAnnotations }}
          annotations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        spec:
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          restartPolicy: Never
          serviceAccountName: {{ include "kub-vol-bak.fullname" . }}-controller
          automountServiceAccountToken: true
          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 12 }}
          containers:
            - name: "restic"
              command:
                - "kub-vol-bak"
                - "backup"
                - "--namespace={{ .Release.Namespace }}"
                - "--config-secret={{ include "kub-vol-bak.fullname" . }}-restic-config"
                - "--image={{ .Values.image.repository }}:{{ .Values.image.tag }}"
              securityContext:
                {{- toYaml .Values.securityContext | nindent 16 }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              resources:
                {{- toYaml .Values.resources | nindent 16 }}
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
