apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "kub-vol-bak.fullname" . }}-prune
  labels:
    {{- include "kub-vol-bak.labels" . | nindent 4 }}
    app.kubernetes.io/component: "prune"
spec:
  schedule: {{ .Values.restic.prune.schedule | quote }}
  suspend: {{ .Values.restic.prune.suspend }}
  concurrencyPolicy: Forbid
  jobTemplate:
    metadata:
      creationTimestamp: null
      labels:
        {{- include "kub-vol-bak.labels" . | nindent 8 }}
        app.kubernetes.io/component: "prune"
    spec:
      backoffLimit: 0 # do not retry this job
      template:
        metadata:
          {{- with .Values.podAnnotations }}
          annotations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        spec:
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          restartPolicy: Never
          serviceAccountName: {{ include "kub-vol-bak.fullname" . }}-controller
          automountServiceAccountToken: true
          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 12 }}
          containers:
            - name: "restic"
              command:
                - "kub-vol-bak"
                - "prune"
                - "--namespace={{ .Release.Namespace }}"
                - "--config-secret={{ include "kub-vol-bak.fullname" . }}-restic-config"
                - "--image={{ .Values.image.repository }}:{{ .Values.image.tag }}"
                {{- if .Values.restic.prune.dryRun }}
                - "--restic-dry-run"
                {{- end }}
              securityContext:
                {{- toYaml .Values.securityContext | nindent 16 }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              resources:
                {{- toYaml .Values.resources | nindent 16 }}
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
