---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "kub-vol-bak.fullname" . }}-controller-role
rules:
# allows creating/viewing/deleting/execing Pods in the current namespace
- apiGroups:
    - ""
  resources:
    - "pods"
    - "pods/attach"
    - "pods/exec"
    - "pods/log"
    # - "pods/portforward"
    # - "pods/proxy"
  verbs:
    - "get"
    - "list"
    - "watch"
    - "create"
    - "patch"
    - "update"
    - "delete"
# allows viewing Secrets in the current namespace
- apiGroups:
    - ""
  resources:
    - "secrets"
  verbs:
    - "get"
    - "list"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kub-vol-bak.fullname" . }}-controller
subjects:
- kind: ServiceAccount
  name: {{ include "kub-vol-bak.fullname" . }}-controller
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "kub-vol-bak.fullname" . }}-controller-role
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kub-vol-bak.fullname" . }}-controller-clusterrole
rules:
# allows viewing PVs and Pods in all namespaces
- apiGroups:
    - ""
  resources:
    - "persistentvolumes"
    - "pods"
  verbs:
    - "get"
    - "list"
# allows viewing and annotating PVCs in all namespaces
- apiGroups:
    - ""
  resources:
    - "persistentvolumeclaims"
  verbs:
    - "get"
    - "list"
    - "patch"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kub-vol-bak.fullname" . }}-controller
subjects:
- kind: ServiceAccount
  name: {{ include "kub-vol-bak.fullname" . }}-controller
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kub-vol-bak.fullname" . }}-controller-clusterrole
