# privileged ServiceAccount for managing backup jobs
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kub-vol-bak.fullname" . }}-controller
  labels:
    {{- include "kub-vol-bak.labels" . | nindent 4 }}
automountServiceAccountToken: false
---
# unprivileged ServiceAccount for performing backups
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kub-vol-bak.fullname" . }}-runner
  labels:
    {{- include "kub-vol-bak.labels" . | nindent 4 }}
automountServiceAccountToken: false
